### ISSUE TITLE
DevOps - Exclude modifications to documentation from triggering a build

### ISSUE THREAD

**Issue by baseTwo** [FirelyTeam/firely-cql-sdk#528]

**Comment by baseTwo** [comment]
Implemented. Closing.

The CI pipeline skips the whole build when every changed file in the push is documentation. `build/azure-pipelines.yml:29-44`:

```yaml
- template: check-skip-stage.yml@templates
  parameters:
    ignorePatterns:
      - '^docs/.+'
      # Any markdown file anywhere - covers CLAUDE.md (root and nested), README.md files,
      # .github/copilot-instructions*.md, and .claude/skills/*/SKILL.md
      - '^.*\.md$'
      # Non-markdown AI instruction/config files (e.g. .claude/settings.local.json)
      - '^\.claude/.+$'

- template: build-test-sign.yml
  parameters:
    buildStageDependsOn: checkSkipStage
    buildStageCondition: and(succeeded(), ne(dependencies.checkSkipStage.outputs['checkChanges.evaluateIgnorePatterns.skip'], 'true'))
```

So the Build stage (and everything gated on it) is conditioned on the skip check. Coverage is broader than the original ask: everything under `docs/`, **any** `*.md` file anywhere in the repo, and the non-markdown AI instruction/config files under `.claude/`.

History: the doc-change skip stage was introduced inline in late 2024 (first `checkForDocChanges` commit `2cc8436a0`, 2024-10-08), replaced by the shared `check-skip-stage.yml@templates` template in `df079e9c9` (2026-05-04, DEVOPS-706), and the pattern list simplified to a single markdown wildcard in `21e8877b1` (2026-07-21) after `e004324f3` added the AI-instruction files.

It is also documented, in both directions:
- `build/README.md:10` — "**checkForDocChangesStage**: Checks if only documentation changed (skips build if so)".
- The contributor-facing consequence is written up in `.github/copilot-instructions/05-build-and-test.md:23` and in the root `CLAUDE.md`: if a PR touches only ignored paths but you *do* want CI to run (e.g. to exercise a skill's shell commands), touch a non-ignored file too.

`build/azure-pipelines.yml` is the only pipeline definition in the repo (`.github/workflows/` is empty), so there is no second pipeline left unguarded.

Confidence: high — the pipeline definition, the condition wiring, and the documentation were all read directly in the current tree.
